version: "3.8"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - ./env/mariadb.env
    volumes:
      - db-volume:/var/lib/mysql  
  
  bot:
    build:
      context: "./src"
      dockerfile: "Mmcc.Bot/Dockerfile"
    restart: unless-stopped
    ports:
      - 5005:5005
    depends_on: 
      - db    

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 5006:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
  db-volume: